# Generated by Django 4.1.6 on 2023-02-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_author_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
    ]
