# Generated by Django 4.1.6 on 2023-02-08 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='likes',
            field=models.ManyToManyField(related_name='podcast', to=settings.AUTH_USER_MODEL),
        ),
    ]
