# Generated by Django 4.1.6 on 2023-02-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_podcast_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='likes',
        ),
    ]
