# Generated by Django 4.1.6 on 2023-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='link',
        ),
        migrations.AddField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='audio_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
