# Generated by Django 4.1.6 on 2023-02-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_category_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='music',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='author',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='category',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='season',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='tags',
        ),
    ]
